//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Device.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IDeviceControl")]
    public interface IDeviceControl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceControl/SendMessage", ReplyAction="http://tempuri.org/IDeviceControl/SendMessageResponse")]
        string SendMessage(int id, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceControl/SendMessage", ReplyAction="http://tempuri.org/IDeviceControl/SendMessageResponse")]
        System.Threading.Tasks.Task<string> SendMessageAsync(int id, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeviceControlChannel : Device.ServiceReference.IDeviceControl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeviceControlClient : System.ServiceModel.ClientBase<Device.ServiceReference.IDeviceControl>, Device.ServiceReference.IDeviceControl {
        
        public DeviceControlClient() {
        }
        
        public DeviceControlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeviceControlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceControlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceControlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendMessage(int id, string message) {
            return base.Channel.SendMessage(id, message);
        }
        
        public System.Threading.Tasks.Task<string> SendMessageAsync(int id, string message) {
            return base.Channel.SendMessageAsync(id, message);
        }
    }
}
